aragon/aragonOS

- contracts/dao/DAOStorage.sol
- contracts/kernel/AbstractKernel.sol
- contracts/kernel/Kernel.sol
- contracts/kernel/organs/DispatcherOrgan.sol
- contracts/kernel/organs/MetaOrgan.sol
- contracts/tokens/EtherToken.sol
- test/dao_create.js
- test/dao_dispatch.js
- test/ether_token.js
- test/helpers/MockedOrgan.sol
- test/helpers/Standard23Token.sol
- test/helpers/StandardTokenPlus.sol
- test/helpers/assertThrow.js
- test/helpers/web3.js
- truffle.js
> Add dispatch tests

- contracts/apps/Application.sol
- contracts/apps/IApplication.sol
- contracts/apps/bylaws/BylawsLib.sol
- contracts/apps/capital/sales/IStockSale.sol
- contracts/apps/capital/sales/StockSale.sol
- contracts/dao/DAOStorage.sol
- contracts/dao/IDAO.sol
- contracts/kernel/IKernel.sol
- contracts/kernel/Kernel.sol
- contracts/kernel/organs/ActionsOrgan.sol
- contracts/kernel/organs/ApplicationOrgan.sol
- contracts/kernel/organs/DispatcherOrgan.sol
- contracts/kernel/organs/IOrgan.sol
- contracts/kernel/organs/MetaOrgan.sol
- contracts/kernel/organs/TokensOrgan.sol
- old_contracts/Company.sol
- old_contracts/ICompany.sol
- old_contracts/accounting/AccountingLib.sol
- old_contracts/factories/CompanyConfiguratorFactory.sol
- old_contracts/sales/IStockSale.sol
- old_contracts/sales/StockSale.sol
- old_contracts/stocks/GovernanceToken.sol
- old_contracts/votes/BinaryPoll.sol
- old_contracts/votes/BinaryVoting.sol
- old_contracts/votes/GenericBinaryVoting.sol
- old_contracts/votes/Voting.sol
- test/mocks/MockedOrgan.sol
Fix https://github.com/aragon/aragon-core/issues/27
> Replace Abstract* for I* for interface like contracts

- contracts/kernel/Kernel.sol
- contracts/kernel/organs/MetaOrgan.sol
- contracts/kernel/organs/VaultOrgan.sol
- contracts/tokens/EtherToken.sol
- package.json
- test/dao_dispatch.js
- test/dao_vault.js
- test/ether_token.js
- test/helpers/timer.js
PR that tracks initial work on the VaultOrgan that will resolve #5.
Interface for current design: 
```
contract IVaultOrgan {
function deposit(address _token, uint256 _amount);
function getTokenBalance(address _token) constant returns (uint256);
function transfer(address _token, address _to, uint256 _amount);
function transferEther(address _to, uint256 _amount);
function halt();
function setHaltTime(uint256 _haltTime);
function getHaltTime() constant returns (uint256);
function scapeHatch(address[] _tokens);
function setScapeHatch(address _scapeHatch);
function getScapeHatch() constant returns (address);
function setTokenBlacklist(address _token, bool _blacklisted);
function isTokenBlacklisted(address _token) constant returns (bool);
}
```
> VaultOrgan implementation

- contracts/tokens/EtherToken.sol
- test/ether_token.js
Inspired by https://gist.github.com/jbaylina/e8ac19b8e7478fd10cf0363ad1a5a4b3
> Implement secureSend for withdraws in ETH token

- .travis.yml
- package.json
- test/dao_dispatch.js
Ethereum signed message gets added by sign function
> Fix signing test for testrpc

- contracts/apps/basic-governance/VotingApp.sol
- contracts/apps/ownership/OwnershipApp.sol
- contracts/kernel/organs/ApplicationOrgan.sol
- test/helpers/web3.js
- test/integration_ownership.js
- test/integration_voting.js
- test/mocks/VotingAppMock.sol
Resolves #24.
WIP, full spec to be written here soon.
> Implement Minime based basic voting

- migrations/2_factory.js
Still has room for improvements - i.e. you have to call initialize yourself and add permissions for all the apps - but it's better than no migrations 😄
> Add basic migrations

- contracts/apps/fundraising/FundraisingApp.sol
- test/apps_fundraising.js
- test/mocks/FundraisingAppMock.sol
All token sales are centralized in the app logic, which allows for upgrading all sales easily.
More work is needed regarding actually buying in sales, right now depending on approve + call and the provisional API for ERC223.
All token sale types are implemented with the same logic, different parametrization will result in different sale flows as opposed to having specific contracts for each of them.
> Fundraising app for v0.5

- .gitignore
- contracts/apps/token-manager/TokenManager.sol
- contracts/apps/voting/VotingApp.sol
- contracts/common/EVMCallScript.sol
- contracts/common/MiniMeToken.sol
- contracts/kernel/Kernel.sol
- entrypoint.sh
Just spent some time to fix the remaining errors while running `npm run lint`, I also added the linting tests to the `entrypoint.sh` so it is runned on travis (and in docker).
> Fix all linting errors

- package-lock.json
- package.json
- test/apps_vault.js
> Added tests for vault contract

- test/apps_group.js
Adds tests for `canForward` and one more for `removeMember`
> Add more tests for group app

- package.json
We need this in order to resolve imports in Solidity for interfaces in this repository.
> Publish Solidity contracts in package

- contracts/apps/fundraising/Fundraising.sol
- test/apps_fundraising.js
- Adds event on buy. Closes #130 
- Enforces sanity checks on initialization
> Fundraising polish

- .soliumrc.json
- contracts/apps/AppProxy.sol
- contracts/common/EtherToken.sol
- contracts/common/MiniMeToken.sol
- contracts/kernel/Kernel.sol
- contracts/kernel/KernelProxy.sol
- contracts/misc/Migrations.sol
Upgrade solium to most recent version and update the configuration file to use updated config syntax. Also added some of the fixes suggested by the linter.
Addresses #147
> Linter upgrade

- contracts/apps/App.sol
- contracts/kernel/IKernel.sol
- contracts/kernel/Kernel.sol
- test/helpers/assertEvent.js
- test/kernel_acl.js
Closes #155 (see issue for explanation and motivation).
If merged, requires changes in AragonOS documentation in the wiki.
> ACL: permission instance parent -> permission owner

- package-lock.json
- package.json
- truffle-config.js
Add gas reporting for tests. Will be used with https://github.com/aragon/aragon-apps/pull/71 to get gas-reporting testing in all aragon app smart contracts.
> Gas reporter

- package-lock.json
- package.json
- readme.md
Closes #183 
Repo name has already been changed. This PR updates npm package.json and readme.
> Repo rename

- readme.md
> Fix README links for aragonOS

- contracts/apm/APMRegistry.sol
- contracts/apps/AragonApp.sol
- contracts/ens/ENSSubdomainRegistrar.sol
>  Add Initialization to AragonApp base

- contracts/acl/ACL.sol
- contracts/apps/AppProxyBase.sol
- contracts/apps/AppProxyPinned.sol
- contracts/apps/AppStorage.sol
- contracts/apps/IAppProxy.sol
- contracts/common/Initializable.sol
- contracts/evmscript/EVMScriptRegistry.sol
- contracts/evmscript/IEVMScriptExecutor.sol
- contracts/evmscript/IEVMScriptRegistry.sol
- contracts/evmscript/executors/CallsScript.sol
- contracts/evmscript/executors/DelegateScript.sol
- contracts/evmscript/executors/DeployDelegateScript.sol
- contracts/factory/APMRegistryFactory.sol
- contracts/factory/DAOFactory.sol
- contracts/factory/EVMScriptRegistryFactory.sol
- contracts/kernel/IACL.sol
- contracts/kernel/IKernel.sol
- contracts/kernel/Kernel.sol
- test/evm_script.js
- test/kernel_acl.js
- test/kernel_apps.js
- test/kernel_upgrade.js
Best way to review is probably to go through each commit and check them; they can all be individually reverted.
> Scripts suggestions

- contracts/apps/AppProxyBase.sol
- test/kernel_apps.js
> Check kernel integrity on AppProxy init

- contracts/kernel/Kernel.sol
- test/kernel_upgrade.js
> Kernel upgrade integrity

- contracts/acl/ACL.sol
- contracts/apm/APMRegistry.sol
- contracts/factory/APMRegistryFactory.sol
- contracts/kernel/Kernel.sol
- migrations/2_apm.js
- migrations/3_factory.js
- package-lock.json
- package.json
- test/apm_registry.js
- test/ens_subdomains.js
- test/mocks/APMRegistryFactoryMock.sol
- truffle-config.js
- Rename roles to new scheme (`keccka256('X_ROLE')`)
- Publish APM apps to APM
- Prepare migration files for being imported from other repos (needed for `aragon-apps/templates`)
Requires publishing NPM patch release on merge
> Add template support

- migrations/2_apm.js
- package-lock.json
- package.json
- scripts/rinkeby-beta-apm.js
- scripts/rinkeby-beta-ens.js
- truffle-config.js
> ENS and APM Rinkeby beta deploy

- contracts/lib/zeppelin/math/SafeMath64.sol
Needed for Voting and Finance apps
> Add SafeMath for uint64

- contracts/common/Initializable.sol
- package.json
- test/kernel_apps.js
- test/mocks/AppStub.sol
Required by https://github.com/aragon/aragon-apps/issues/188
> Add modifier to check for already initialized apps

- contracts/apps/AppProxyUpgradeable.sol
> Remove dangling storage in AppProxyUpgradeable

- contracts/factory/AppProxyFactory.sol
> AppProxyFactory: log whether proxy is pinned or upgradeable

- contracts/factory/DAOFactory.sol
It has been tested with Aragon apps Beta templates.
Closes #217.
> Clean up permissions granted to factories

- contracts/evmscript/executors/DeployDelegateScript.sol
> Fix storage shadowing in DeployDelegateScript cache

- contracts/evmscript/executors/CallsScript.sol
- test/evm_script.js
> CallsScript: check overflows

- contracts/acl/ACL.sol
- test/kernel_acl.js
> Remove ACL checks on granting and revoking to avoid lock because of params

- contracts/acl/ACL.sol
- test/kernel_acl.js
> acl: Add better getters for extracting ACL info

- contracts/acl/ACL.sol
- contracts/factory/DAOFactory.sol
- test/kernel_acl.js
> ACL: add removePermissionManager()

- contracts/common/DelegateProxy.sol
- contracts/evmscript/executors/DelegateScript.sol
- test/TestDelegateProxy.sol
- test/evm_script.js
- test/mocks/DelegateScriptWrapper.sol
To save one extcodesize in that case.
> Add address 0 check to isContract

- contracts/apps/AppProxyBase.sol
- contracts/apps/AppProxyPinned.sol
- contracts/apps/AppProxyUpgradeable.sol
- contracts/apps/IAppProxy.sol
- contracts/kernel/Kernel.sol
- contracts/kernel/KernelProxy.sol
- contracts/kernel/KernelStorage.sol
- contracts/lib/misc/ERCProxy.sol
- test/kernel_apps.js
- test/kernel_upgrade.js
> Make AppProxies and KernelProxy ERC897 compatible

- contracts/factory/AppProxyFactory.sol
> AppProxyFactory: emit appId in NewAppProxy event

- package.json
> Add repo URL to package.json

- .travis.yml
- scripts/ganache-cli.sh
Updates `ganache-cli.sh` to `aragon-apps`' version.
> Add test task to Travis CI

- migrations/2_apm.js
- migrations/3_factory.js
- migrations/4_links.js
Solves #365 using the pattern seen here: https://github.com/trufflesuite/truffle/issues/501
> Fix truffle migration async scripts

- contracts/common/DepositableDelegateProxy.sol
- contracts/lib/minime/MiniMeToken.sol
- test/mocks/EncodeMock.sol
- test/mocks/VaultMock.sol
> Make fallbacks external

- package.json
0.5.8 has some performance improvements during instrumentation.
> Upgrade solidity-coverage

- contracts/acl/ACL.sol
Use the common time helpers, for safe uint64 conversion.
> ACL: use TimeHelpers

- contracts/lib/math/SafeMath64.sol
- contracts/lib/math/SafeMath8.sol
- contracts/test/mocks/SafeMath64Mock.sol
- contracts/test/mocks/SafeMath8Mock.sol
- test/lib_safemath64.js
- test/lib_safemath8.js
Plus add tests for them.
Small optimizations avoiding one extra division. Tested on Remix.
> lib: optimize multiplication for SafeMath64 and SafeMath8

- contracts/apm/Repo.sol
Intentionally didn't modify the tests to make sure the internal change doesn't affect how the repo works.
> Change Repo version storage from an array to a mapping

- scripts/deploy-daofactory.js
Needed for https://github.com/aragon/dao-kits/pull/32
> Make EVMScriptRegistryFactory optional for DAO factory

- LICENSE
Given https://github.com/aragon/dao-kits/pull/56#discussion_r240984858, and with the general recommendation that we should include the license short text in every file, I've opted to modify the text to "assume" that this short text is on every file.
> chore: update license text

- test/recovery_to_vault.js
> test: remove accidentally placed .only() in tests

- contracts/apm/APMRegistry.sol
- contracts/apm/Repo.sol
- contracts/kernel/Kernel.sol
Changes some of the radspec strings to be more consistent in style.
> fix: update radspec strings for a few contracts

- package.json
Issue with ganache-core has now been fixed :tada:
> chore: upgrade ganache-cli to 6.4.2

- scripts/deploy-daofactory.js
Needed for the Aragon 0.7 re-deployment of kits, which will have an upgraded `DAOFactory` but keeping the bases for `ACL` and `Kernel` of the current deployment.
> chore: allow to skip deploying Kernel and ACL bases in deploy-daofactory

- truffle-config.js
> Add development network to truffle config
