index.js, package.json
This PR implements my proposed fixes in #3.
The package is now publishable to npm. Before publishing, npm will build all of the contracts using truffle.
A package entrypoint is provided that loops over all contracts in the build directory and exposes them as a plain object.
Including the example file from the proposal I wrote:
```js
// This is an example of how you could use the package
const contracts = require('aragon-core')
// All of the contracts are exposed in the package as you would expect,
// so a contract named e.g. ``KeybaseRegistry`` would be accessible in
// ``contracts.KeybaseRegistry``.
// One could then interact with them through a package like ``truffle-contract``
const provider = new Web3.providers.HttpProvider('http://localhost:8545')
const contract = …
```
=> Module packaging (fixes #3)

package.json
When building from scratch, `npm t` fails with a missing babel-polyfill dependency. 
It may be unnoticed on TravisCI because `node_modules` is cached across builds.
```
root@aragon-core:/usr/src/app# npm t
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.0
npm info lifecycle aragon-core@1.0.0~pretest: aragon-core@1.0.0
npm info lifecycle aragon-core@1.0.0~test: aragon-core@1.0.0
> aragon-core@1.0.0 test /usr/src/app
> truffle test
Error: Cannot find module 'babel-polyfill'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/usr/src/app/truffle.js:2:1)
at Module._compile (module.js:570:32)
at …
```
=> Add missing npm dependency

contracts/kernel/organs/ApplicationOrgan.sol, migrations/2_deploy_dao.js, migrations/3_install_apps.js, migrations/4_basic_setup.js, test/helpers/web3.js, truffle.js
Closes #41.
Built on top of #39, given that it is the most advanced version that works. 
Needed to implement manual nonce management to allow parallel organ and application deployment.
I was able to successfully deploy and configure the [first aragon-core DAO in the testnet](https://kovan.etherscan.io/address/0xa4805523e75bc9baa1abad3a71a4016b61957993) 🎉
=> Basic migration that deploys a functional DAO

contracts/factories/BasicFactory.sol, contracts/organs/MetaOrgan.sol, npm-shrinkwrap.json, package.json, scripts/generate_factory.js
Fixes #79
Had forgotten to publish our own fork of [`solidity-structure`](https://www.npmjs.com/package/solidity-structure) that `scripts/generate-factory.js` uses to get the needed annotations from source code files.
Running `truffle exec scripts/generate_factory.js` will analyze all Solidity files and generate `BasicFactory.sol` following the a Handlebars template saved at `BasicFactory.sol.tmpl`
=> Fix solidity-inspector being a local dependency by publishing it to npm

package.json
In order to take full advantages of #80, adding the `npm run generate:factory` command.
=> Add generate:factory command

contracts/apps/basic-governance/IVotingApp.sol, contracts/apps/bylaws/IBylawsApp.sol, contracts/apps/ownership/IOwnershipApp.sol, contracts/apps/ownership/OwnershipApp.sol, contracts/apps/status/IStatusApp.sol, contracts/factories/ForwarderFactory.sol, contracts/organs/IVaultOrgan.sol
Closes #78.
Adding keyword `indexed` to more variables in different events, this should allow an easier filtering of the different events (for instance, see all actions about a specific token).
=> Index more events

contracts/apps/Application.sol, contracts/apps/IApplication.sol, contracts/apps/basic-governance/VotingApp.sol, contracts/kernel/Kernel.sol, contracts/misc/DAOMsg.sol, contracts/organs/IOrgan.sol, contracts/organs/IVaultOrgan.sol, contracts/organs/VaultOrgan.sol, test/dao_msg.js, test/dao_vault.js, test/helpers/DAOMsgOrgan.sol
Fixes #30 
`dao_msg` is the form of passing context about the call to DAO components (organs and apps). It is similar to Solidity's `msg.x` which cannot be trusted given that calls to the DAO can be made through multiple entrypoints and get routed through the kernel.
`dao_msg` exposes the true`sender` of the transaction, the `token` the transaction was made with and its `value`.
Prior to this PR, right before dispatching the call to the specific DAO component, the dao_msg data was saved in storage (in the case of organs, in DAO storage and in the case of apps, a call to the app was made and the app saved it). This approach was fairly expensive gas wise (3 extra sstore's per call) and was also vulnerable to race conditions in case a call reentered in the DAO as explained in #30 
It is …
=> Call context (dao_msg) now gets passed as part of calldata

.gitignore, contracts/apps/Application.sol, contracts/apps/basic-governance/IVotingApp.sol, contracts/apps/bylaws/BylawsApp.sol, contracts/apps/bylaws/IBylawsApp.sol, contracts/apps/ownership/IOwnershipApp.sol, contracts/apps/ownership/OwnershipApp.sol, contracts/apps/status/IStatusApp.sol, contracts/factories/BasicFactory.sol, contracts/factories/ForwarderFactory.sol, contracts/organs/IVaultOrgan.sol, contracts/organs/MetaOrgan.sol, npm-shrinkwrap.json, package.json, scripts/function_analysis.js, scripts/generate_factory.js, test/helpers/web3.js, test/integration_bylaws.js
This PR focuses on improving security of multiple things:
- Bylaw ids being incremental integers were vulnerable to chain reorg attacks (submit a bylaw and expect it to have id x and it end up being y). Now the bylaw id is a hash of the parameters of the bylaw so it is deterministic. 
- Makes sure the DAO reference of an app cannot be changed once it has been set.
=> Change bylaw ids from incremental integers to hashes and other security measures

contracts/apps/bylaws/BylawsApp.sol, contracts/kernel/Kernel.sol, test/helpers/Standard23Token.sol, test/integration_bylaws.js
Hello @izqui 
Here's the current state of the contracts. I've done this in different forms but never managed to make it work.
All tests(introduced by me) are failing for different reasons:
`'correctly sets an whitlisted token'` is failing with: `could not unlock signer account`. Which I presume is because I'm trying to send from the dao address, but I could not go around this since the function itself is protected with `onlyDao` modifier.
`allows non listed token deposit` throws somewhere. I honestly don't know why.
The last two `blocks non listed token exectuion` and ` allows listed token execution` are incomplete, because I'm getting `Invalid number of arguments to Solidity function`, even though there are two signatures of the `transfer` function in `Standard23Token` and one of them …
=> Added token whitelist [Draft]

contracts/apps/basic-governance/IVotingApp.sol, contracts/apps/basic-governance/VotingApp.sol, contracts/apps/bylaws/BylawsApp.sol, contracts/apps/bylaws/IBylawsApp.sol, contracts/apps/ownership/IOwnershipApp.sol, contracts/apps/ownership/OwnershipApp.sol, contracts/apps/status/IStatusApp.sol, contracts/apps/status/StatusApp.sol, contracts/factories/BasicFactory.sol, contracts/factories/BasicFactory.sol.tmpl, contracts/factories/ForwarderFactory.sol, contracts/organs/IMetaOrgan.sol, contracts/organs/MetaOrgan.sol
Closes #89.
Made all events to the present tense, so it fits zeppelin's tense (`Transfer` etc).
=> Standardize events' tense

.solcover.js, contracts/apps/App.sol, contracts/apps/voting/EVMScriptRunner.sol, contracts/apps/voting/VotingApp.sol, contracts/common/MiniMeToken.sol, package-lock.json, package.json, test/apps_voting.js, test/helpers/ExecutionTarget.sol
Implements the new voting app for v0.5 in which the app is its own identity (no need to have individual vote contracts any more).
In this initial implementation no voting metadata is saved on chain. Should we include any? Should that be a string saved on-chain or a reference to a content addressable document in IPFS or Swarm? cc @luisivan 
What a voting will execute is determined by its `executionScript`.  The script allows multiple actions to be voted in just one voting allowing more complex workflows.
A script is just a bytes array that contains an arbitrary number of (destination address, calldata) pairs. When executed, the voting app will do as many `CALL` as specified in the script. In case one of the calls fails or it goes out of gas, the entire execution is reverted.
The script …
=> Implement Entity based VotingApp

contracts/apps/vault/Vault.sol
Very simple initial version for the Vault for the Finance app to interact with (cc @readevalprint)
The rationale behind it is, the Finance App (or other apps allowed to access funds) should interact with the Vault by calling `requestAllowances` with the budgeted amounts when a period starts. Once it is allowed to spend, the Finance app won't have to call the Vault on every transfer, it will be able to just do `token.transferFrom(vault, recipient, amount)`.
=> Implement Vault for tokens

package.json
Based on the new repo structure, the script generating the factory has been removed, just cleaning the command using it.
=> Remove factory script

contracts/apps/token-manager/TokenManager.sol, test/apps_fundraising.js, test/apps_tokenmanager.js
Creates two different initializers for the two modes a Token Manager can be in.
=> Split Token Manager initializers based on mode

contracts/apps/voting/Voting.sol, test/apps_voting.js
- Save snapshot of minimum acceptance quorum of every vote. Closes #129 
- Instead of returning a hash of the evm call script, return the entire script.
- Remove useless `vote.open` boolean from storage.
- Improve calculations for support and min quorum for small quorums
=> Voting app polish

contracts/common/DelegateProxy.sol, contracts/common/EtherToken.sol, contracts/zeppelin/token/BasicToken.sol, contracts/zeppelin/token/StandardToken.sol, package-lock.json, package.json, test/ether_token.js, test/evm_call_script.js, test/helpers/assertThrow.js, test/kernel_acl.js, test/kernel_apps.js, test/kernel_upgrade.js, test/mini_me_token.js, test/zeppelin_StandardToken.js
Also updates Zeppelin's token contracts to the latest version to avoid failure with SafeMath assertions
=> Adapt tests for Byzantium revert's and remove pre-Byzantium logic from DelegateProxy

contracts/apps/AppProxy.sol, contracts/common/DelegateProxy.sol, test/kernel_apps.js, test/mocks/AppStub.sol
Closes #144 
Adds the ability to provide a payload to be executed when an AppProxy is deployed. This allows to perform an atomic deployment and initialization of any app without the need to have a specific factory.
It shouldn't introduce any security vulnerabilities as the proxy will forward any call in the same way after it being deployed.
**TODO:** Needs documentation update on the wiki
=> Add ability to execute initialization payload on AppProxy deployment

.babelrc, package-lock.json, package.json, truffle-config.js
=> Remove babel

contracts/common/EVMCallScript.sol
Adding this event will allow to recover forwarding paths from transaction receipts. This is needed to properly show the side-effects of a given transaction in components such as the tx queue (https://github.com/aragon/aragon/issues/63)
=> Add LogScriptCall to allow tracing forwards

.soliumrc.json, contracts/apps/App.sol, contracts/apps/AppProxy.sol, contracts/apps/AppStorage.sol, contracts/common/DelegateProxy.sol, contracts/common/EVMCallScript.sol, contracts/common/EtherToken.sol, contracts/common/IForwarder.sol, contracts/common/Initializable.sol, contracts/common/MiniMeToken.sol, contracts/common/TokenController.sol, contracts/common/erc677/ERC677Receiver.sol, contracts/common/erc677/ERC677Token.sol, contracts/kernel/IKernel.sol, contracts/kernel/Kernel.sol, contracts/kernel/KernelProxy.sol, contracts/kernel/KernelStorage.sol, contracts/misc/Migrations.sol, contracts/zeppelin/math/SafeMath.sol, package-lock.json, package.json, scripts/ganache-cli.sh, test/kernel_apps.js, test/mocks/AppStub.sol, test/mocks/ERC677Stub.sol, test/mocks/ExecutionTarget.sol, test/mocks/Executor.sol, test/mocks/UpgradedKernel.sol, truffle-config.js
Closes #167 
Also locks critical contracts to 0.4.18 and 'interfaces' to `^0.4.18`, so it closes #158 and closes #160 (cc @sohkai please review this)
Didn't bother to update anything ERC677 or MiniMe as those are getting replace soon.
=> solc update to 0.4.18 (use view and pure 🎉)

contracts/apps/AppProxy.sol
Using `>` feels less correct that `!=` given that addresses don't really make sense having "greater" or "lesser" comparisons.
=> Use != for address checks

contracts/apps/App.sol, test/mocks/AppStub.sol
=> Renaming 'App' contract to 'AragonApp'

contracts/common/Initializable.sol, test/kernel_acl.js
~Not sure if there was a plan to make more use of these functions in `Initializable`, but as they are it doesn't really make sense to keep them.~
Adds a few comments to `Initializable` for implementation details.
=> Add comments to Initializable

contracts/factory/APMRegistryFactory.sol, contracts/factory/DAOFactory.sol, contracts/factory/EVMScriptRegistryFactory.sol, contracts/kernel/Kernel.sol, test/evm_script.js, test/kernel_acl.js, test/kernel_apps.js
Allows users of our Kernel implementation to deploy app instances directly from the kernel.
The most common use case would be when an existing DAO finds a new app they want to install. Rather than having to spend two transactions to separately deploy a `AppProxy` and invoke `kernel.setApp()`, they could just do `kernel.newAppInstance()`. Actually "installing" the app would still take another transaction, to set the permissions.
This change also allows the kernel's initialization to directly spawn an ACL app, rather than expecting it to be provided from the outside. I think this makes sense, as "initializing" the kernel should set everything essential (only ACL right now) up for you.
=> Kernel is AppProxyFactory

.solcover.js, contracts/acl/ACL.sol, contracts/acl/ACLSyntaxSugar.sol, contracts/apps/AragonApp.sol, package-lock.json, test/TestACLInterpreter.sol, test/helpers/ACLHelper.sol, test/kernel_apps.js, test/mocks/AppStub.sol
Looks like we might need to release aOS 3.0.1 earlier than expected 😅
=> Improvements for App support: add authP modifiers in AragonApp base and add more syntax sugar

test/mini_me_token.js
Not wanting to throw out accusations or whatever but the minime tests are a mess, let me give you samples:
- there are [unused imports](https://github.com/aragon/aragonOS/blob/dev/test/mini_me_token.js#L1)
- at least one test is failing because of a [forgotten await](https://github.com/aragon/aragonOS/blob/dev/test/mini_me_token.js#L88)
- there is at least one [contradictory statements](https://github.com/aragon/aragonOS/blob/dev/test/mini_me_token.js#L101)
- [this test](https://github.com/aragon/aragonOS/blob/dev/test/mini_me_token.js#L94) is actually totally wrong since we are using `accounts[0]` as the source of ethereum transactions: based on [the minime code](https://github.com/aragon/aragonOS/blob/dev/contracts/lib/minime/MiniMeToken.sol#L172) the controller doesn't need any …
=> Fix minime tests

package.json
Truffle@4.0.6 upgrades solidity to 0.4.19, which breaks our fixed contracts.
=> Pin truffle to 4.0.5

package.json
Some of the templates are requiring the aragonOS migrations and will fail if these aren't included in the published package.
=> Add migrations folder in published package

contracts/lib/minime/ITokenController.sol
`onTransfer()` and `onApprove()` are arbitrary and should be allowed to modify state (e.g. keeping a list of transferees).
Needed for https://github.com/aragon/aragon-apps/pull/104.
=> ITokenController: remove constant modifier

package.json
Generally you want to use `&&` when chaining to avoid running the second step if the first step fails.
=> Use && rather than ; in npm scripts

contracts/common/DelegateProxy.sol, test/TestDelegateProxy.sol, test/helpers/ThrowProxy.sol
Adds a new param to `delegateFwd(...)` to pass the minimum amount of bytes the underlying call must return, otherwise, it reverts. I kept the old function as a convenince method that just passes `0` as the minimum return data size.
This allows things such as always forcing to return something when calling a specific type of contract to avoid a `selfdesctruct`. Given that when a `selfdestruct` occurs the context is exited returning `1` (success) but always returns 0 bytes of data. Ideally this would be done at the protocol level, returning a different error code when it `selfdestruct`s but we can't wait.
This only works if you force the functions you forward to return something (setting the min to 32 and returning a boolean is enough).
=> delegatecall safety: Implement min return size in DelegateProxy

contracts/factory/ENSFactory.sol
> for ENSFactory.js import "./ENSConstants.sol" instead of import "../ens/ENSSubdomainRegistrar.sol"
=> ENSFactory: import ENSConstants instead of ENSSubdomainRegistrar

contracts/apps/AragonApp.sol
adriamb:
> Seems that AragonApp does not need to be a EVMScriptRunner
ji:
> we decided to add it to the baseclass instead of requiring every app to add it
adriamb:
> Cool, I think that is good idea to annotate this decision in the code. Code readers usually expect that some functionality is used when a class implements another"
=> AragonApp: add comments for inheriting from ACLSyntaxSugar, EVMScriptRunner

contracts/acl/ACL.sol
adriamb:
> https://github.com/aragon/aragonOS/blob/dev/contracts/acl/ACL.sol#L311 > (r1 && !r2) || (!r1 && r2);  why not to use the ^ xor operator?
ji:
> i didn't know the operator was available in solidity
------------
XOR for two booleans is simply `!=` :).
=> ACL: simplify XOR op

contracts/factory/DAOFactory.sol
> Currently there is a superfluous ternary being used in the DAOFactory.sol function newDAO when only 1 conditinal is necessary.
=> DAOFactory: remove unnecessary ternary

contracts/common/IVaultRecoverable.sol, contracts/common/VaultRecoverable.sol, test/mocks/AppStubConditionalRecovery.sol, test/proxy_recover_funds.js
Adds the `allowRecoverability(address token)` function that can be overwritten by apps to block recoverability of certain tokens. 
Blocking recoverability is important for some apps that hold assets themselves, otherwise an organization with 2 vaults can have all funds moved to the default vault.
=> Implement and test conditional recoverability

contracts/kernel/Kernel.sol
😰 I think I messed this up a while back.
=> Kernel: fix no returns from overloads of newAppInstance()

contracts/apm/APMConstants.sol, contracts/apm/APMNamehash.sol, test/mocks/APMNamehash.sol, test/mocks/APMNamehashWrapper.sol
Exposes `APMNamehash.sol` to let packages like the DAO kits to get an APM namehash without reimplementing it.
=> Expose APMNamehash

LICENSE, contracts/acl/ACLSyntaxSugar.sol, contracts/acl/IACL.sol, contracts/apps/AppStorage.sol, contracts/apps/AragonApp.sol, contracts/common/EtherTokenConstant.sol, contracts/common/IForwarder.sol, contracts/common/IVaultRecoverable.sol, contracts/common/Initializable.sol, contracts/common/IsContract.sol, contracts/common/VaultRecoverable.sol, contracts/ens/ENSConstants.sol, contracts/evmscript/EVMScriptRunner.sol, contracts/evmscript/IEVMScriptExecutor.sol, contracts/evmscript/IEVMScriptRegistry.sol, contracts/evmscript/ScriptHelpers.sol, contracts/kernel/IKernel.sol, contracts/lib/misc/ERCProxy.sol, package.json
See https://spdx.org/using-spdx-license-identifier and https://spdx.org/sites/cpstandard/files/pages/files/using_spdx_license_list_short_identifiers.pdf.
=> Relicense interface and extendible contracts as MIT

package.json
Seems like we forgot to do this in aragonOS 😅
=> Truffle console is now truffle dev

contracts/acl/ACL.sol, contracts/apm/APMRegistry.sol, contracts/apm/Repo.sol
Default to `public` unless there's a good reason (e.g. a custom getter).
=> Explicitly state state visibility

contracts/kernel/Kernel.sol, test/kernel_apps.js
`kernelIntegrity` has been made obsolete with the changes to check that addresses given to `setApp()` are always contracts (f7680657).
The only appropriate check `kernelIntegrity` could do is make sure that the base kernel is still a kernel contract, but this is impossible without something like a public `isKernel()` (which may not be a bad idea, as it also helps frontends).
=> Kernel: remove kernelIntegrity modifier

contracts/evmscript/EVMScriptRunner.sol, test/evm_script.js
From https://github.com/ConsenSys/aragon-apps-audit-repo/issues/32:
> The _executeVote function executes an EVMScript if a vote has sufficient support. The result of the execution is not logged nor is checked if it throws an exception.
=> EVMScriptRunner: add ScriptResult log

.solcover.js, contracts/acl/ACL.sol, contracts/acl/IACLOracle.sol, contracts/evmscript/EVMScriptRegistry.sol, contracts/evmscript/EVMScriptRunner.sol, contracts/evmscript/IEVMScriptRegistry.sol, contracts/factory/AppProxyFactory.sol, contracts/factory/DAOFactory.sol, contracts/factory/EVMScriptRegistryFactory.sol, contracts/kernel/Kernel.sol, contracts/kernel/KernelProxy.sol, contracts/lib/minime/MiniMeToken.sol, test/TestACLInterpreter.sol, test/TestAclOracle.sol, test/helpers/ACLHelper.sol
From https://github.com/ConsenSys/aragonOS-audit-repo/issues/14:
> Avoid using the address type for contract references. Instead use the actual contract type or an interface to statically restrict the different possible configurations that your contracts can be composed into.
-------------
Some parameters or state are left to be `address` due to their dynamic nature.
=> Add more static contract types to state and function parameters

contracts/apps/AragonApp.sol, contracts/common/Initializable.sol, contracts/kernel/Kernel.sol
**The current tests haven't been adjusted (and new tests need to be added) so CI will be breaking**
Depends on #355.
Adds checks for initialization when checking if someone can perform an action (either `hasPermission()` or `canPerform()` in the `Kernel` and `AragonApp`, respectively). This solves 90% of the instances where people will need to add `isInitialized` in the face of the new requirement that all public-facing state-changing functions must check for initialization.
=> [Prototype] Check for initialization during access control check

contracts/acl/ACL.sol, contracts/apm/APMRegistry.sol, contracts/apm/Repo.sol, contracts/apps/AragonApp.sol, contracts/apps/UnsafeAragonApp.sol, contracts/common/Autopetrified.sol, contracts/common/Petrifiable.sol, contracts/evmscript/EVMScriptRegistry.sol, contracts/evmscript/EVMScriptRunner.sol, contracts/evmscript/executors/BaseEVMScriptExecutor.sol, contracts/evmscript/executors/CallsScript.sol, contracts/factory/EVMScriptRegistryFactory.sol
Experiments with #355, adding a few ideas:
1. `AragonApp` (c5806bf): default behaviour is to petrify immediately on deployment
1. `UnsafeAragonApp` (6ac3cb4): freestyle mode, for app developers. Removes all safety defaults (only `initializationBlock` for now) and lets the developer play with fire. Useful for mocking in tests too.
1. `Autopetrified` (ee28768): provide helper to petrify immediately on deployment
1. `EVMScriptExecutor` (17b12c1): petrify the executors, so that they can't be used outside of a `delegatecall` originating from an initialized contract (ideally an `EVMScriptRunner`).
Comments and tests to be adjusted.
=> [Prototype] Default bases to petrified

test/time_helpers.js
I think if there's a split second change between the requests for time, we get back different values.
It should never be more than one second off.
=> Make time helper tests more robust by giving a bit of leeway

contracts/apps/AppProxyPinned.sol, contracts/apps/AppStorage.sol, contracts/common/Initializable.sol, contracts/common/UnstructuredStorage.sol, migrations/2_apm.js, test/apm_registry.js, test/ens_subdomains.js, test/keccak_constants.js, test/mocks/AppStubPinnedStorage.sol, test/mocks/AppStubStorage.sol, test/unstructured_storage.js
Also moves the `pinnedCode` implementation details to `AppProxyPinned` as it's only relevant there, and unstructured storage is meant to hide these types of abstractions :).
=> Make UnstructuredStorage a library

contracts/evmscript/EVMScriptRegistry.sol
Fixes #384.
Named it `Enable` in case we add functionality to re-enable executors in the future.
=> EVMScriptRegistry: emit events on adding and disabling executors

contracts/evmscript/IEVMScriptExecutor.sol, contracts/evmscript/executors/CallsScript.sol, test/evm_script.js, test/keccak_constants.js, test/mocks/KeccakConstants.sol
Was getting worried that we always assume in `aragon.js` that the first executor in an organization's `EVMScriptRegistry` is the callscript executor, rather than doing an on-chain confirmation.
**TODO**:
=> EVMScriptExecutor: add type for off-chain reading

migrations/2_apm.js, migrations/3_factory.js, test/apm_registry.js, test/apm_repo.js, test/app_acl.js, test/app_base_lifecycle.js, test/app_proxy.js, test/ens_subdomains.js, test/evm_script.js, test/helpers/assertThrow.js, test/helpers/onlyIf.js, test/kernel_acl.js, test/kernel_apps.js, test/kernel_lifecycle.js, test/kernel_upgrade.js, test/lifecycle.js, test/mocks/APMRegistryFactoryMock.sol, test/mocks/AppStub.sol, test/mocks/AppStubConditionalRecovery.sol, test/mocks/AppStubStorage.sol, test/mocks/ERCProxyMock.sol, test/mocks/EVMScriptExecutor.sol, test/mocks/LifecycleMock.sol, test/mocks/MockScriptExecutorApp.sol, test/mocks/UnsafeAragonAppMock.sol, test/mocks/UnsafeRepo.sol, test/mocks/UpgradedKernel.sol, test/proxy_recover_funds.js, test/unstructured_storage.js
All the contract changes can be seen in #355.
Quite a lot of the tests have been revamped, mainly to support parametrization across different base / proxy targets. Also found a few tests that were outdated or completely broken (in terms of what they were testing) 😄.
=> Petrifiable: add tests

contracts/factory/DAOFactory.sol
Small cosmetic change to make it more clear what the `DAOFactory` is doing to clean up permissions.
=> DAOFactory: clarify permissions clean up

contracts/apps/AppProxyPinned.sol, contracts/common/Initializable.sol, contracts/kernel/KernelProxy.sol, test/app_proxy.js, test/keccak_constants.js, test/kernel_apps.js, test/kernel_upgrade.js, test/mocks/AppStubPinnedStorage.sol, test/mocks/KernelOverloadMock.sol, test/mocks/KernelSetAppMock.sol, test/unstructured_storage.js
Adds more contract checks to the proxies.
Bytecode change:
```
AppProxyPinned.json Same                 0                  -18
KernelProxy.json    Same                 0                  +126
```
=> Proxies: add checks for base being a contract

.soliumrc.json, contracts/evmscript/EVMScriptRegistry.sol
=> Update linter for 0.4.24 features

contracts/common/IForwarder.sol
See https://github.com/ethereum/solidity/issues/4832.
There are a few other cases in our interfaces where this applies (`bytes` or array parameter in an `external` interface), but implementations of those cases shouldn't require casting the visibility to `public`:
- `IACLOracle#canPerform()`
- `IEVMScriptExecutor#execScript()`
=> IForwarder: change interfaces to public instead of external due to solidity bug

contracts/acl/ACL.sol
I guess we forgot to do it when we moved the ACL out of the Kernel
=> Use auth modifier for createPermissions

contracts/acl/ACL.sol
From https://github.com/aragon/aragonOS/pull/397#issuecomment-417321833.
Details how the ACL is implicitly protected by `hasInitialized()`.
=> ACL: add notes about lifecycle safety

contracts/apps/AppProxyBase.sol, contracts/evmscript/EVMScriptRunner.sol, contracts/evmscript/IEVMScriptRegistry.sol, contracts/kernel/IKernel.sol, contracts/kernel/Kernel.sol, contracts/kernel/KernelConstants.sol, contracts/kernel/KernelProxy.sol, contracts/kernel/KernelStorage.sol, contracts/test/mocks/KeccakConstants.sol, contracts/test/mocks/KernelSetAppMock.sol, test/keccak_constants.js, test/kernel_apps.js, test/kernel_lifecycle.js, test/proxy_recover_funds.js
Fixes #337.
I've opted to keep the "app identifier" nomenclature rather than "app name" due to it breaking less external interfaces (e.g. events). A name and an identifier are pretty similar anyway, we just shouldn't have both concepts.
=> Kernel: use explicit mapping for namespaces rather than hash

truffle-config.js
Consolidates the configuration for different networks. It will now look for a key file for the network under `~/.aragon/[network]key.json` and use the keys and RPC specified in the file. If no keys are found, then it will default to using the user defined mnemonic or the default mnemonic. As for the RPC, it will use the one in the key file, and if that is not present, it will use the infura endpoint for the network.
Because we are now lazy loading providers, we can remove the need for having the `LIVE_NETWORKS` environment variable set to true when interacting with live networks, as if one of the networks that aren't being used cannot be connected to it is not a problem.
=> Clean up truffle-config.js and lazy load providers

scripts/deploy-beta-apm.js, scripts/deploy-beta-ens.js, scripts/deploy-daofactory.js
Adds optional parameters to the deployment scripts to allow them to be used by other scripts being executed by `truffle exec`.
`deploy-beta-apm.js` automatically deploys a custom ENS if none is provided.
Also adds a script for deploying `DAOFactory`.
=> Modular deployment scripts

test/kernel_acl.js
Adds some more tests about the ACL's lifecycle constraints, now that it's petrified by default.
=> ACL: add more tests about initialization

contracts/factory/APMRegistryFactory.sol, contracts/factory/EVMScriptRegistryFactory.sol, contracts/kernel/Kernel.sol, contracts/test/mocks/APMRegistryFactoryMock.sol, contracts/test/mocks/KernelOverloadMock.sol, test/kernel_apps.js
`AppProxyFactory` exposes the ability to pass an initialization payload that app proxies execute on their constructor. This PR exposes this ability at the Kernel level, so apps can be atomically initialized when they are created.
=> Kernel: allow initializing app proxies on overloaded newAppInstance

contracts/factory/APMRegistryFactory.sol
Verify that the owner of the TLD is the APMRegistryFactory itself before setSubnodeOwner is invoked.
The [ENS.sol](https://github.com/aragon/aragonOS/blob/dev/contracts/lib/ens/ENS.sol) from lib has the modifier `only_owner` that throws in case `setSubnodeOwner` is invoked by someone who isn't the owner.
However it seems that this isn't the behavior of the ENS-Registry (0x314159265dD8dbb310642f98f50C066173C1259b) which doesn't make a throw/revert. It returns a "Bad jump destination" so it won't refund the remaining gas
=> Check that the owner of the TLD is the APMRegistryFactory itself before setSubnodeOwner

.gitignore, package.json
Fixes #369.
Extracts the abi on publish, so that frontends don't have to include the entire build artifact in their bundles.
Example extracted abi (for `Petrify.sol`):
```
{
"abi": [
{
"constant": true,
"inputs": [],
"name": "hasInitialized",
"outputs": [
{
"name": "",
"type": "bool"
}
],
"payable": false,
"stateMutability": "view",
"type": "function"
},
{
"constant": true,
"inputs": [],
"name": "getInitializationBlock",
"outputs": [
{
"name": "",
"type": "uint256"
}
],
"payable": false,
"stateMutability": "view",
"type": "function"
},
{
"constant": true,
"inputs": [],
"name": "isPetrified",
"outputs": [
{
"name": "",
"type": "bool"
}
],
"payable": false,
"stateMutability": "view",
"type": "function"
}
]
}
```
=> Publish ABI

truffle-config.js
Fixes #389.
As far as I can tell from the gas test reporter and bytecode comparisons, we never lose at 10k runs. However, the gas test reporter is unreliable due to it also includes the deployment cost in a lot of cases (which are always lower).
=> Enable optimization for 10k runs

contracts/acl/ACL.sol, contracts/apm/APMNamehash.sol, contracts/apm/APMRegistry.sol, contracts/apm/Repo.sol, contracts/apps/AppProxyPinned.sol, contracts/common/DelegateProxy.sol, contracts/common/EtherTokenConstant.sol, contracts/common/Petrifiable.sol, contracts/ens/ENSConstants.sol, contracts/ens/ENSSubdomainRegistrar.sol, contracts/evmscript/EVMScriptRegistry.sol, contracts/evmscript/IEVMScriptRegistry.sol, contracts/evmscript/executors/BaseEVMScriptExecutor.sol, contracts/evmscript/executors/CallsScript.sol, contracts/kernel/Kernel.sol, contracts/kernel/KernelConstants.sol, contracts/lib/misc/ERCProxy.sol, contracts/test/mocks/AppProxyPinnedStorageMock.sol, contracts/test/mocks/AppStub.sol, contracts/test/mocks/ERCProxyMock.sol, contracts/test/mocks/EVMScriptExecutorMock.sol, contracts/test/mocks/KeccakConstants.sol
Generally, visibility modifers are preferred before any other modifier (strong social consensus, e.g. OpenZeppelin).
Our linter doesn't have a rule to check this yet (see https://github.com/duaraghav8/Solium/issues/239).
=> Fix visibility order for constants

contracts/kernel/KernelConstants.sol
Use non-strict version to be able to import aragon contracts on Remix & Etheratom.
`KernelConstants` is eventually used by `AragonApp`.
=> KernelConstants: use nonstrict pragma

contracts/apps/AragonApp.sol, contracts/kernel/Kernel.sol
When using the native call syntax `target.method(...)` solc introduces
a check for the code size of the target (and reverts if it is 0), therefore
we don't need to manually ensure that the target address is not 0 before making
a call, as the size of the address 0 will be 0, and therefore already revert
=> Remove redundant kernel check in AragonApp.getRecoveryVault()

scripts/deploy-beta-apm.js, scripts/deploy-daofactory.js
Makes the DAOFactory deployment script accept a parameter to not deploy an `EVMScriptRegistryFactory`, and changes the APM deployment script to directly use the DAOFactory deployment script.
=> Deployment: use DAOFactory deployment in APM deployment

contracts/acl/ACL.sol, contracts/apm/APMRegistry.sol, contracts/apm/Repo.sol, contracts/apps/AragonApp.sol, contracts/common/Initializable.sol, contracts/common/Uint256Helpers.sol, contracts/common/VaultRecoverable.sol, contracts/ens/ENSSubdomainRegistrar.sol, contracts/evmscript/EVMScriptRegistry.sol, contracts/evmscript/EVMScriptRunner.sol, contracts/evmscript/executors/CallsScript.sol, contracts/kernel/Kernel.sol, contracts/lib/math/SafeMath.sol, contracts/lib/math/SafeMath64.sol, contracts/lib/math/SafeMath8.sol
=> Revert reasons

contracts/evmscript/EVMScriptRunner.sol, test/evm_script.js
From https://github.com/aragon/aragonOS/pull/443#discussion_r227039851.
Since this will most commonly be exposed as part of an `AragonApp`, I've opted to make the two functions more explicit (note that this is a breaking public interface change).
=> [BREAKING CHANGE] EVMScriptRunner: expose getEVMScriptRegistry

truffle-config.js
Needed for dao-kits, to automatically choose network from scripts. Right now it's overlapping with `rpc`.
=> Change devnet (docker image) network id

scripts/deploy-apm.js, scripts/deploy-test-ens.js, scripts/helpers/get-accounts.js
When using a real ENS (on mainnet) `setSubdomainOwner` would fail as the deployed won't be the owner of the `eth` TLD.
Also 8bb2d81 fixes the scripts failing as `util.promisify` is not available inside the `truffle exec` execution context.
=> deploy-apm: Implement name transfer instead of always creating subnode

contracts/acl/ACL.sol, contracts/apps/AragonApp.sol, contracts/kernel/Kernel.sol
From https://github.com/ConsenSys/aragonOS-audit-repo/issues/46:
> The `how` object in the `AragonApp.canPerform` function depends on possibly undefined Solidity behavior. Due to the sensitive nature of the function, we recommend initializing the `how` variable when `_params.length == 0` to avoid the possibility of a vulnerability.
------------------
I tried removing all the logic related to casting to/from bytes and uint arrays to their own separate contract or libraries, but in both cases the bytecode diff was extreme (+50k to +120k in gas) so I've opted not to consolidate and just align all the comments.
Bytecode comparison:
```
ACL.json                       1600 less gas        -8                 0
APMRegistry.json …
```
=> AragonApp: fix possibly uninitialized bytes array when checking permissions

contracts/factory/EVMScriptRegistryFactory.sol
We forgot to remove it when the factory started using `dao.newPinnedAppInstance` to create instances.
=> chore EVMScriptRegistryFactory: remove unused AppProxyFactory base contract

contracts/kernel/IKernel.sol, contracts/kernel/KernelProxy.sol, package.json, test/helpers/decodeEvent.js, test/kernel_upgrade.js
Fixes #457 by allowing a frontend to follow all `SetApp()` events emitted from the start of a KernelProxy's lifespan.
=> KernelProxy: emit SetApp event on construction

package.json
Check with the CI that `ganache-cli@6.2.3` and `ganache-core@2.3.1` are not breaking our tests.
=> chore: pin ganache-cli to 6.2.3

contracts/common/SafeERC20.sol, contracts/common/VaultRecoverable.sol, contracts/test/mocks/SafeERC20Mock.sol, test/safe_erc20.js
Builds on #469.
Adds some `staticcall` utilities to the `ERC20` interface, as before solidity 0.5 these `balanceOf()` and `allowance()` functions were not called with a `staticcall`.
Useful for cases like [here](https://github.com/aragon/aragonOS/pull/470/files#diff-32170f8bb97d146f323f07e8ee82f9acR35), [here](https://github.com/aragon/aragon-apps/blob/master/apps/finance/contracts/Finance.sol#L362), or [here](https://github.com/aragon/aragon-apps/blob/master/apps/vault/contracts/Vault.sol#L77) where users may be unsuspecting of a function actually calling out to another contract (that may be malicious).
Bytecode diff:
```
ACL.json                       48600 more gas       +243               0
APMRegistry.json …
```
=> feat(SafeERC20): add static call utilities

.solcover.js, contracts/common/SafeERC20.sol, contracts/common/VaultRecoverable.sol, contracts/test/mocks/SafeERC20Mock.sol, contracts/test/mocks/TokenMock.sol, contracts/test/mocks/TokenReturnFalseMock.sol, contracts/test/mocks/TokenReturnMissingMock.sol, test/proxy_recover_funds.js, test/recovery_to_vault.js, test/safe_erc20.js, test/time_helpers.js
Required for https://github.com/aragon/aragon-apps/issues/562.
Adds a `SafeERC20` library that should be used to enhance `ERC20` types. The `safeTransfer()`, `safeTransferFrom()`, and `safeApprove()` methods ensure standards-compliance (e.g. always returning a value) with different token interfaces in the wild.
Note that the change for `VaultRecoverable.sol` means every `AragonApp` is affected.
Bytecode comparison:
```
ACL.json                       49200 more gas       +246               0
APMRegistry.json               50600 more gas       +253               0
AppStub.json                   49000 more gas       +245               0
AppStub2.json                  49200 more gas       +246               0 …
```
=> feat: Add SafeERC20

contracts/test/mocks/APMRegistryFactoryMock.sol, test/apm_registry.js, test/ens_subdomains.js, test/evm_script.js
Improves the coverage of some missing branches.
=> tests: Coverage improvements

contracts/common/IVaultRecoverable.sol, contracts/common/VaultRecoverable.sol, test/recovery_to_vault.js
Not sure if we made a conscious decision before to not emit an event, but it seems useful to know about for frontends and successful recoveries.
=> VaultRecoverable: emit event on successful recovery

contracts/lib/ens/AbstractENS.sol, contracts/lib/ens/ENS.sol, contracts/lib/ens/PublicResolver.sol
Not sure if single quotes was ever recommended, but the docs now only use double quotes for the import syntax.
Also adds links to where these ENS contracts are derived from.
=> fix: Use double quotes in contract imports

test/apm_registry.js, test/apm_repo.js, test/ens_subdomains.js, test/evm_script.js, test/kernel_acl.js, test/kernel_apps.js, test/kernel_lifecycle.js, test/recovery_to_vault.js
Updates the tests to use `EMPTY_BYTES` and `ZERO_ADDR` constants (should move these out to a shared lib sometime).
Also fixes a few instances where we sent an invalid number of hex bytes (usually 1-length bytes like `0x1`; see https://github.com/trufflesuite/ganache-core/issues/283#issuecomment-470997764).
=> test: update bytes and address constants

contracts/acl/ACLSyntaxSugar.sol
This is actually [used by the Voting app](https://github.com/aragon/aragon-apps/blob/master/apps/voting/contracts/Voting.sol#L196) currently, although it never assigns to the array.
=> ACLSyntaxSugar: fix returning unallocated memory

contracts/apps/AragonApp.sol, contracts/common/ReentrancyGuard.sol, contracts/test/mocks/KeccakConstants.sol, contracts/test/mocks/ReentrancyGuardMock.sol, test/keccak_constants.js, test/reentrancy_guard.js, test/unstructured_storage.js
Adds a reusable `ReentrancyGuard` working off of its own unstructured storage slot, and makes it available to `AragonApp`s.
See https://github.com/aragon/aragon-apps/pull/744#discussion_r271393365 for context.
-----------
Bytecode comparison:
```
KeccakConstants.json 28400 more gas       +142               0
```
But the actual bytecode increase of adding the `nonReentrant` modifier is ~60k gas per use.
=> feat: add ReentrancyGuard

contracts/acl/ACL.sol, contracts/apps/AragonApp.sol, contracts/common/ConversionHelpers.sol, contracts/kernel/Kernel.sol, contracts/test/TestConversionHelpers.sol, test/conversion_helpers.js, test/helpers/decodeEvent.js, test/helpers/runSolidityTest.js
Consolidates all the bytes<>uint256[] conversions into a library.
It's not _too_ costly to add, and hopefully makes us all feel a bit better about this bit 😄.
Also fixes the solidity test runner, which must've broke at some point along the way (due to the assert logs not being decoded properly) 😅.
Bytecode diff:
```
ACL.json                      5400 more gas        +27                0
APMRegistry.json              4400 more gas        +22                0
AragonApp.json                4000 more gas        +20                0
ENSSubdomainRegistrar.json    4000 more gas        +20                0
EVMScriptRegistry.json        4000 more gas        +20                0
EVMScriptRegistryFactory.json Same                 0 …
```
=> feat: add ConversionHelpers lib for converting memory types

contracts/common/ConversionHelpers.sol, contracts/test/TestConversionHelpers.sol
There are publicly exposed interfaces that expect `bytes` and immediately turn them into `uint256[]` (e.g. `hasPermission()` in the ACL and Kernel.
There might be some cases where the truncation could lead to Bad Things<sup>TM</sup>, like the ACL being tricked into thinking a contract had permission to do something when it actually didn't. We never use the `bytes` form of `hasPermission()` directly ourselves, so this isn't exploitable, but could be if an external contract decided to.
With help from @wadeAlexC.
Bytecode diff (`AragonApp` doesn't use `dangerouslyCastBytesToUintArray()`):
```
ACL.json                   33200 more gas       +166               0
TestACLInterpreter.json    33200 more gas       +166               0 …
```
=> ConversionHelpers: check length on bytes to uint256[]

contracts/test/TestDelegateProxy.sol, test/evm_script.js, test/helpers/runSolidityTest.js, test/lifecycle.js
Adds some improvements to the test suite, as per the Consensys Diligence advisory.
=> Testing improvements

test/helpers/assertThrow.js
The `assertRevert` helper was using the `actual` and `expected` values swapped. This was causing misleading logs while testing an unsuccessful scenario.
=> Helpers: Fix assert revert helper

contracts/common/IForwarderFee.sol
Should go into a 4.2.1 release for https://github.com/aragon/tollgate.
=> Add IForwarderFee

contracts/common/DepositableDelegateProxy.sol, contracts/test/helpers/EthSender.sol, contracts/test/helpers/ProxyTarget.sol, contracts/test/mocks/apps/DepositableDelegateProxyMock.sol, package.json, test/contracts/apps/app_funds.js, test/contracts/apps/recovery_to_vault.js, test/contracts/common/depositable_delegate_proxy.js, test/contracts/kernel/kernel_funds.js, test/helpers/assertThrow.js
Optimizes the fallback function in the proxy so it can receive ETH after EIP-1884 is implemented in Istanbul. 
With these changes, the gas cost for executing the fallback function has gone down **from 1759 gas to 1619**, which after the SLOAD opcode is repriced to 800 gas will still execute under 2300 gas (2219 gas).
Closes #549 (even though this issue doesn't tackle the potential migration for all existing DAOs whose Vaults would break)
=> DepositableDelegateProxy: optimize for EIP-1884

contracts/acl/ACLSyntaxSugar.sol, contracts/acl/IACL.sol, contracts/acl/IACLOracle.sol, contracts/apm/APMNamehash.sol, contracts/apps/AppStorage.sol, contracts/apps/AragonApp.sol, contracts/apps/UnsafeAragonApp.sol, contracts/common/Autopetrified.sol, contracts/common/EtherTokenConstant.sol, contracts/common/IForwarder.sol, contracts/common/IForwarderFee.sol, contracts/common/IVaultRecoverable.sol, contracts/common/Initializable.sol, contracts/common/IsContract.sol, contracts/common/Petrifiable.sol, contracts/common/ReentrancyGuard.sol, contracts/common/TimeHelpers.sol, contracts/common/UnstructuredStorage.sol, contracts/common/VaultRecoverable.sol, contracts/ens/ENSConstants.sol, contracts/evmscript/EVMScriptRunner.sol, contracts/evmscript/IEVMScriptExecutor.sol, contracts/evmscript/IEVMScriptRegistry.sol, contracts/evmscript/ScriptHelpers.sol, contracts/evmscript/executors/BaseEVMScriptExecutor.sol, contracts/kernel/IKernel.sol, contracts/kernel/KernelConstants.sol, contracts/lib/misc/ERCProxy.sol
Even though it was fun to spot projects reusing or forking aragon contracts: https://github.com/search?q=SPDX-License-Identitifer&type=Code
But I thought it might be interesting to fix the misspelling, in case any automated script might eventually parse that header to show the license.
Related: https://github.com/aragon/aragon-apps/pull/1013
=> License: replace SPDX-Identifier misspelling in contract headers

package.json, test/contracts/common/depositable_delegate_proxy.js, test/helpers/coverage.js, truffle-config.js
Updates the tests to drop the deprecated Constantinople context.
Skips the `solidity-coverage@0.7` upgrade for now, to avoid too much churn. We will do this later.
=> chore: Update to Istanbul context

contracts/acl/ACL.sol, contracts/test/helpers/ACLHelper.sol, contracts/test/tests/TestACLInterpreter.sol, test/contracts/acl/acl_params.js, test/helpers/coverage.js, test/helpers/permissionParams.js
This PR will enable the 1Hive Oracles to function as expected since the Istanbul hard fork. Unfortunately our Oracles `canPerform()` functions can not be guaranteed to execute under the gas limit of `30000`.
Relevant functions in the Oracles can be seen here:
https://github.com/1Hive/token-oracle/blob/master/contracts/TokenBalanceOracle.sol#L59
https://github.com/1Hive/dandelion-voting-app/blob/master/contracts/DandelionVoting.sol#L252
I've replaced the Oracle `canPerform()` `staticcall` gas limit of `30000` with `gasleft()` minus some amount for returning an error (preventing a revert if the `staticcall` runs out of gas). As suggested by @sohkai.
I've observed that if the `staticcall` reverts with an oog after being given all of `gasleft()` it still seems to reserve about `100000` gas, …
=> ACL: remove ACLOracle canPerform() gas limit

package.json
Reverts the move of this dependency to `devDependencies`. We still export our `truffle-config.js` from this package and would not be able to safely stop doing this until we release a major version (otherwise every dependent expecting to use the truffle config will break).
cc @0xGabi
=> chore: move @aragon/truffle-config-v4 to dependency

scripts/deploy-daofactory.js
Similar to `KernelBase` and `ACLBase`, adds the ability to specify a known `EvmScriptRegistryFactory` when deploying `DAOFactory`.
=> deploy: skip deploying known EvmScriptRegistryFactory if given to DAOFactory
